# Generated by Django 3.0.4 on 2020-03-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviewportal', '0002_interview_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interview',
            name='id',
        ),
        migrations.AlterField(
            model_name='interview',
            name='count',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
